site_name: Deoxy Docs
site_dir: build/docs

use_directory_urls: false

theme:
  name: readthedocs
  locale: pt_BR
  highlightjs: true
  hljs_languages:
    - yaml
    - cpp
    - c
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 3
  sticky_navigation: true

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: pt
          name: Portugues
          build: true
          nav_translations:
            Home: Inicio
            Getting Started: Começando
            Installation: Instalação
            Quick Start: Inicio Rápido
            Features and Guides: Recursos e Guias
            Window System: Sistema de Janela
            Input System: Sistema de Input
            Rendering and Graphics: Renderização e Gráficos
            UI and GUI: Interface e GUI
            Utilities, Logs and Assertions: Utilidades, Logs e Assertions
            More: Mais
            API Reference: Referência da API
            Language: Idioma

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
  - Features and Guides:
      - Window System: guides/window.md
      - Input System: guides/input.md
      - Rendering and Graphics: guides/graphics.md
      - UI and GUI: guides/gui.md
      - Utilities, Logs and Assertions: guides/utilities.md
  - More:
    - API Reference: /DeoxyLib/api/
  - Language:
      - 🇺🇸 English: /DeoxyLib/
      - 🇧🇷 Português: /DeoxyLib/pt/

markdown_extensions:
  - admonition
  - toc:
      permalink: "🛈"